<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- 项目配置 -->
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <!-- 代码分析 -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>

  </PropertyGroup>

  <ItemGroup>
    <!-- NUnit 包 -->
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- 项目引用 -->
    <ProjectReference Include="..\src\Csanno.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- 引用生成器作为 Analyzer -->
    <ProjectReference Include="..\src\Csanno.Generator\Csanno.Generator.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all"
                      OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
