using System.Collections.Generic;
using System.Linq;
using System.Text;
using Csanno.Generator.Models;

namespace Csanno.Generator.Emit;

/// <summary>
/// 代理类代码发射器
/// </summary>
internal sealed class ProxyEmitter
{
    /// <summary>
    /// 生成代理类代码
    /// </summary>
    public string GenerateProxyClasses(
        string assemblyName,
        IEnumerable<ProxyInfo> proxies,
        IEnumerable<InterceptorInfo> interceptors)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Assembly: {assemblyName}");
        sb.AppendLine("// AOP Proxy Classes");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using Csanno.Attributes;");
        sb.AppendLine();

        var interceptorsList = interceptors.ToList();

        foreach (var proxy in proxies.Where(p => p.HasInterceptedMethods))
        {
            GenerateProxyClass(sb, proxy, interceptorsList);
        }

        return sb.ToString();
    }

    private void GenerateProxyClass(
        StringBuilder sb,
        ProxyInfo proxy,
        List<InterceptorInfo> interceptors)
    {
        // 命名空间
        sb.AppendLine($"namespace {proxy.Namespace}");
        sb.AppendLine("{");

        // 代理类定义
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 自动生成的代理类：{proxy.ClassName}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public class {proxy.ClassName}_Proxy : {proxy.FullTypeName}");
        sb.AppendLine("    {");

        // 静态 MethodInfo 字段
        foreach (var method in proxy.InterceptedMethods)
        {
            var paramTypes = method.Parameters.Count > 0
                ? $", new System.Type[] {{ {string.Join(", ", method.Parameters.Select(p => $"typeof({p.Type})"))} }}"
                : "";
            sb.AppendLine($"        private static readonly MethodInfo _{ToCamelCase(method.MethodName)}Method = typeof({proxy.FullTypeName}).GetMethod(\"{method.MethodName}\"{paramTypes})!;");
        }
        sb.AppendLine();

        // 拦截器字典字段（按注解类型分组）
        sb.AppendLine("        private readonly Dictionary<System.Type, IInterceptor[]> _interceptorsByAttribute;");
        sb.AppendLine();

        // 生成构造函数
        GenerateConstructors(sb, proxy, interceptors);

        // 生成拦截方法
        foreach (var method in proxy.InterceptedMethods)
        {
            GenerateInterceptedMethod(sb, method);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateConstructors(
        StringBuilder sb,
        ProxyInfo proxy,
        List<InterceptorInfo> interceptors)
    {
        // 收集所有需要的注解类型
        var allAttributeTypes = proxy.InterceptedMethods
            .SelectMany(m => m.InterceptorAttributeTypes)
            .Distinct()
            .ToList();

        foreach (var ctor in proxy.Constructors)
        {
            // 构造函数参数：拦截器集合 + 原始参数
            var interceptorParam = "System.Collections.Generic.IEnumerable<IInterceptor> interceptors";
            var originalParams = string.Join(", ", ctor.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var allParams = ctor.Parameters.Count > 0
                ? $"{interceptorParam}, {originalParams}"
                : interceptorParam;

            // 基类构造函数调用
            var baseArgs = string.Join(", ", ctor.Parameters.Select(p => p.Name));

            sb.AppendLine($"        public {proxy.ClassName}_Proxy({allParams})");
            if (ctor.Parameters.Count > 0)
            {
                sb.AppendLine($"            : base({baseArgs})");
            }
            sb.AppendLine("        {");
            sb.AppendLine("            var interceptorList = interceptors.ToList();");
            sb.AppendLine("            _interceptorsByAttribute = new Dictionary<System.Type, IInterceptor[]>();");
            sb.AppendLine();

            // 为每个注解类型筛选拦截器
            foreach (var attrType in allAttributeTypes)
            {
                // 找到绑定到这个注解的拦截器类型
                var boundInterceptors = interceptors
                    .Where(i => i.BoundAttributeTypes.Contains(attrType))
                    .Select(i => i.FullTypeName)
                    .ToList();

                if (boundInterceptors.Count > 0)
                {
                    var typeChecks = string.Join(" || ", boundInterceptors.Select(t => $"i is {t}"));
                    sb.AppendLine($"            _interceptorsByAttribute[typeof({attrType})] = interceptorList.Where(i => {typeChecks}).ToArray();");
                }
                else
                {
                    sb.AppendLine($"            _interceptorsByAttribute[typeof({attrType})] = System.Array.Empty<IInterceptor>();");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private void GenerateInterceptedMethod(StringBuilder sb, MethodInterceptInfo method)
    {
        // 方法签名
        var returnType = method.ReturnsVoid ? "void" : method.ReturnType;
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));

        sb.AppendLine($"        public override {returnType} {method.MethodName}({parameters})");
        sb.AppendLine("        {");

        // 参数数组
        if (method.Parameters.Count > 0)
        {
            var args = string.Join(", ", method.Parameters.Select(p => p.Name));
            sb.AppendLine($"            var args = new object?[] {{ {args} }};");
        }
        else
        {
            sb.AppendLine("            var args = System.Array.Empty<object?>();");
        }

        // 收集所有拦截器
        sb.AppendLine("            var allInterceptors = new List<IInterceptor>();");
        foreach (var attrType in method.InterceptorAttributeTypes)
        {
            sb.AppendLine($"            if (_interceptorsByAttribute.TryGetValue(typeof({attrType}), out var interceptors_{attrType.Replace(".", "_")}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                allInterceptors.AddRange(interceptors_{attrType.Replace(".", "_")});");
            sb.AppendLine("            }");
        }
        sb.AppendLine();

        // OnBefore
        sb.AppendLine("            foreach (var interceptor in allInterceptors)");
        sb.AppendLine("            {");
        sb.AppendLine($"                interceptor.OnBefore(_{ToCamelCase(method.MethodName)}Method, args);");
        sb.AppendLine("            }");
        sb.AppendLine();

        // 调用基类方法
        var baseArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
        if (method.ReturnsVoid)
        {
            sb.AppendLine($"            base.{method.MethodName}({baseArgs});");
            sb.AppendLine();
            sb.AppendLine("            foreach (var interceptor in allInterceptors)");
            sb.AppendLine("            {");
            sb.AppendLine($"                interceptor.OnAfter(_{ToCamelCase(method.MethodName)}Method, null);");
            sb.AppendLine("            }");
        }
        else
        {
            sb.AppendLine($"            var result = base.{method.MethodName}({baseArgs});");
            sb.AppendLine();
            sb.AppendLine("            foreach (var interceptor in allInterceptors)");
            sb.AppendLine("            {");
            sb.AppendLine($"                interceptor.OnAfter(_{ToCamelCase(method.MethodName)}Method, result);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return result;");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
