using System.Collections.Generic;
using System.Linq;
using System.Text;
using Csanno.Generator.Models;

namespace Csanno.Generator.Emit;

/// <summary>
/// 代理类代码发射器
/// </summary>
internal sealed class ProxyEmitter
{
    /// <summary>
    /// 生成代理类代码
    /// </summary>
    public string GenerateProxyClasses(
        string assemblyName,
        IEnumerable<ProxyInfo> proxies,
        IEnumerable<InterceptorInfo> interceptors)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Assembly: {assemblyName}");
        sb.AppendLine("// AOP Proxy Classes");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using Csanno.Attributes;");
        sb.AppendLine();

        var interceptorsList = interceptors.ToList();

        foreach (var proxy in proxies.Where(p => p.HasInterceptedMethods))
        {
            GenerateProxyClass(sb, proxy, interceptorsList);
        }

        return sb.ToString();
    }

    private void GenerateProxyClass(
        StringBuilder sb,
        ProxyInfo proxy,
        List<InterceptorInfo> interceptors)
    {
        // 命名空间
        sb.AppendLine($"namespace {proxy.Namespace}");
        sb.AppendLine("{");

        // 代理类定义
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// 自动生成的代理类：{proxy.ClassName}");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public class {proxy.ClassName}_Proxy : {proxy.FullTypeName}");
        sb.AppendLine("    {");

        // 静态 MethodInfo 字段
        foreach (var method in proxy.InterceptedMethods)
        {
            var paramTypes = method.Parameters.Count > 0
                ? string.Join(", ", method.Parameters.Select(p => $"typeof({p.Type})"))
                : "";
            var fieldSuffix = method.Parameters.Count > 0 ? $"_{method.Parameters.Count}" : "";
            sb.AppendLine($"        private static readonly MethodInfo _{ToCamelCase(method.MethodName)}{fieldSuffix}Method = typeof({proxy.FullTypeName}).GetMethod(\"{method.MethodName}\", new System.Type[] {{ {paramTypes} }})!;");
        }
        sb.AppendLine();

        // 拦截器字典字段（按注解类型分组，包含 InvokeType）
        sb.AppendLine("        private readonly Dictionary<System.Type, (IInterceptor interceptor, InvokeType invokeType)[]> _interceptorsByAttribute;");
        sb.AppendLine();

        // 生成构造函数
        GenerateConstructors(sb, proxy, interceptors);

        // 生成拦截方法
        foreach (var method in proxy.InterceptedMethods)
        {
            GenerateInterceptedMethod(sb, method);
        }

        // 生成 ComputeShouldInvoke 辅助方法
        GenerateComputeShouldInvokeMethod(sb);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void GenerateComputeShouldInvokeMethod(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 根据 OnBefore 结果和 InvokeType 计算是否应该调用原生方法");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static bool ComputeShouldInvoke(List<(IInterceptor interceptor, InvokeType invokeType)> interceptors, List<bool> results)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (interceptors.Count == 0) return true;");
        sb.AppendLine();
        sb.AppendLine("            // 位掩码计算");
        sb.AppendLine("            int mask = 0;");
        sb.AppendLine("            for (int i = 0; i < results.Count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (results[i]) mask |= (1 << i);");
        sb.AppendLine("            }");
        sb.AppendLine("            int allTrue = (1 << results.Count) - 1;");
        sb.AppendLine();
        sb.AppendLine("            // 检查各 InvokeType 规则（优先级：MustInvoke > NeverInvoke > 其他）");
        sb.AppendLine("            bool hasMustInvoke = false, hasNeverInvoke = false;");
        sb.AppendLine("            for (int i = 0; i < interceptors.Count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (interceptors[i].invokeType)");
        sb.AppendLine("                {");
        sb.AppendLine("                    case InvokeType.MustInvoke: hasMustInvoke = true; break;");
        sb.AppendLine("                    case InvokeType.NeverInvoke: hasNeverInvoke = true; break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (hasMustInvoke) return true;");
        sb.AppendLine("            if (hasNeverInvoke) return false;");
        sb.AppendLine();
        sb.AppendLine("            // 检查其他条件（WhenAnyTrue, WhenAnyFalse, 默认 WhenAllTrue）");
        sb.AppendLine("            for (int i = 0; i < interceptors.Count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                switch (interceptors[i].invokeType)");
        sb.AppendLine("                {");
        sb.AppendLine("                    case InvokeType.WhenAnyTrue:");
        sb.AppendLine("                        if (mask != 0) return true;");
        sb.AppendLine("                        break;");
        sb.AppendLine("                    case InvokeType.WhenAnyFalse:");
        sb.AppendLine("                        if (mask != allTrue) return true;");
        sb.AppendLine("                        break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 默认: WhenAllTrue - 所有返回 true 时调用");
        sb.AppendLine("            return mask == allTrue;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void GenerateConstructors(
        StringBuilder sb,
        ProxyInfo proxy,
        List<InterceptorInfo> interceptors)
    {
        // 收集所有需要的注解类型
        var allAttributeTypes = proxy.InterceptedMethods
            .SelectMany(m => m.InterceptorAttributeTypes)
            .Distinct()
            .ToList();

        foreach (var ctor in proxy.Constructors)
        {
            // 构造函数参数：拦截器集合 + 原始参数
            var interceptorParam = "System.Collections.Generic.IEnumerable<IInterceptor> interceptors";
            var originalParams = string.Join(", ", ctor.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var allParams = ctor.Parameters.Count > 0
                ? $"{interceptorParam}, {originalParams}"
                : interceptorParam;

            // 基类构造函数调用
            var baseArgs = string.Join(", ", ctor.Parameters.Select(p => p.Name));

            sb.AppendLine($"        public {proxy.ClassName}_Proxy({allParams})");
            if (ctor.Parameters.Count > 0)
            {
                sb.AppendLine($"            : base({baseArgs})");
            }
            sb.AppendLine("        {");
            sb.AppendLine("            var interceptorList = interceptors.ToList();");
            sb.AppendLine("            _interceptorsByAttribute = new Dictionary<System.Type, (IInterceptor, InvokeType)[]>();");
            sb.AppendLine();

            // 为每个注解类型筛选拦截器并关联 InvokeType
            foreach (var attrType in allAttributeTypes)
            {
                // 找到绑定到这个注解的拦截器及其 InvokeType
                var boundInterceptors = interceptors
                    .SelectMany(i => i.Bindings
                        .Where(b => b.AttributeType == attrType)
                        .Select(b => new { i.FullTypeName, b.InvokeType }))
                    .ToList();

                if (boundInterceptors.Count > 0)
                {
                    sb.AppendLine($"            _interceptorsByAttribute[typeof({attrType})] = interceptorList");
                    sb.AppendLine($"                .Select(i => {{");
                    
                    // 为每个拦截器类型生成判断逻辑
                    var first = true;
                    foreach (var bi in boundInterceptors)
                    {
                        var prefix = first ? "                    " : "                    else ";
                        sb.AppendLine($"{prefix}if (i is {bi.FullTypeName}) return (i, InvokeType.{bi.InvokeType});");
                        first = false;
                    }
                    sb.AppendLine("                    else return (null!, InvokeType.Default);");
                    sb.AppendLine($"                }})");
                    sb.AppendLine($"                .Where(x => x.Item1 != null)");
                    sb.AppendLine($"                .ToArray();");
                }
                else
                {
                    sb.AppendLine($"            _interceptorsByAttribute[typeof({attrType})] = System.Array.Empty<(IInterceptor, InvokeType)>();");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private void GenerateInterceptedMethod(StringBuilder sb, MethodInterceptInfo method)
    {
        // 方法签名
        var returnType = method.ReturnsVoid ? "void" : method.ReturnType;
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));

        sb.AppendLine($"        public override {returnType} {method.MethodName}({parameters})");
        sb.AppendLine("        {");

        // 参数数组
        if (method.Parameters.Count > 0)
        {
            var args = string.Join(", ", method.Parameters.Select(p => p.Name));
            sb.AppendLine($"            var args = new object?[] {{ {args} }};");
        }
        else
        {
            sb.AppendLine("            var args = System.Array.Empty<object?>();");
        }

        // 收集所有拦截器（带 InvokeType）
        sb.AppendLine("            var allInterceptors = new List<(IInterceptor interceptor, InvokeType invokeType)>();");
        foreach (var attrType in method.InterceptorAttributeTypes)
        {
            var safeName = attrType.Replace(".", "_");
            sb.AppendLine($"            if (_interceptorsByAttribute.TryGetValue(typeof({attrType}), out var interceptors_{safeName}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                allInterceptors.AddRange(interceptors_{safeName});");
            sb.AppendLine("            }");
        }
        sb.AppendLine();

        // 嵌套调用链实现
        sb.AppendLine("            // 记录 OnBefore 结果");
        sb.AppendLine("            var results = new List<bool>();");
        sb.AppendLine("            int index = 0;");
        sb.AppendLine("            var invokeResult = new InvokeResult();");
        
        if (method.ReturnsVoid)
        {
            sb.AppendLine();
            GenerateNestedCallChainVoid(sb, method);
        }
        else
        {
            sb.AppendLine($"            {method.ReturnType} result = default!;");
            sb.AppendLine();
            GenerateNestedCallChainWithReturn(sb, method);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private void GenerateNestedCallChainVoid(StringBuilder sb, MethodInterceptInfo method)
    {
        var baseArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
        var fieldSuffix = method.Parameters.Count > 0 ? $"_{method.Parameters.Count}" : "";
        var methodField = $"_{ToCamelCase(method.MethodName)}{fieldSuffix}Method";

        sb.AppendLine("            void InvokeChain()");
        sb.AppendLine("            {");
        sb.AppendLine("                if (index < allInterceptors.Count)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var (interceptor, invokeType) = allInterceptors[index++];");
        sb.AppendLine("                    bool onBeforeSucceeded = false;");
        sb.AppendLine("                    try");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        bool r = interceptor.OnBefore({methodField}, args, invokeResult);");
        sb.AppendLine("                        results.Add(r);");
        sb.AppendLine("                        onBeforeSucceeded = true;");
        sb.AppendLine("                        InvokeChain();");
        sb.AppendLine("                    }");
        sb.AppendLine("                    catch (System.Exception ex) when (!onBeforeSucceeded)");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        bool shouldContinue = interceptor.OnBeforeException({methodField}, args, ex, invokeResult);");
        sb.AppendLine("                        if (shouldContinue)");
        sb.AppendLine("                        {");
        sb.AppendLine("                            results.Add(true);");
        sb.AppendLine("                            InvokeChain();");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                    finally");
        sb.AppendLine("                    {");
        sb.AppendLine("                        try");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            interceptor.OnAfter({methodField}, null);");
        sb.AppendLine("                        }");
        sb.AppendLine("                        catch (System.Exception ex)");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            interceptor.OnAfterException({methodField}, null, ex);");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 计算是否调用原生方法");
        sb.AppendLine("                    bool shouldInvoke = ComputeShouldInvoke(allInterceptors, results);");
        sb.AppendLine("                    if (shouldInvoke)");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        base.{method.MethodName}({baseArgs});");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            InvokeChain();");
    }

    private void GenerateNestedCallChainWithReturn(StringBuilder sb, MethodInterceptInfo method)
    {
        var baseArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
        var fieldSuffix = method.Parameters.Count > 0 ? $"_{method.Parameters.Count}" : "";
        var methodField = $"_{ToCamelCase(method.MethodName)}{fieldSuffix}Method";

        sb.AppendLine("            void InvokeChain()");
        sb.AppendLine("            {");
        sb.AppendLine("                if (index < allInterceptors.Count)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var (interceptor, invokeType) = allInterceptors[index++];");
        sb.AppendLine("                    bool onBeforeSucceeded = false;");
        sb.AppendLine("                    try");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        bool r = interceptor.OnBefore({methodField}, args, invokeResult);");
        sb.AppendLine("                        results.Add(r);");
        sb.AppendLine("                        onBeforeSucceeded = true;");
        sb.AppendLine("                        InvokeChain();");
        sb.AppendLine("                    }");
        sb.AppendLine("                    catch (System.Exception ex) when (!onBeforeSucceeded)");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        bool shouldContinue = interceptor.OnBeforeException({methodField}, args, ex, invokeResult);");
        sb.AppendLine("                        if (shouldContinue)");
        sb.AppendLine("                        {");
        sb.AppendLine("                            results.Add(true);");
        sb.AppendLine("                            InvokeChain();");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                    finally");
        sb.AppendLine("                    {");
        sb.AppendLine("                        try");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            interceptor.OnAfter({methodField}, result);");
        sb.AppendLine("                        }");
        sb.AppendLine("                        catch (System.Exception ex)");
        sb.AppendLine("                        {");
        sb.AppendLine($"                            interceptor.OnAfterException({methodField}, result, ex);");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 计算是否调用原生方法");
        sb.AppendLine("                    bool shouldInvoke = ComputeShouldInvoke(allInterceptors, results);");
        sb.AppendLine("                    if (shouldInvoke && !invokeResult.HasValue)");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        result = base.{method.MethodName}({baseArgs});");
        sb.AppendLine("                        invokeResult.SetValue(result);");
        sb.AppendLine("                    }");
        sb.AppendLine("                    else if (invokeResult.HasValue)");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        result = ({method.ReturnType})invokeResult.Value!;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            InvokeChain();");
        sb.AppendLine("            if (invokeResult.HasValue)");
        sb.AppendLine("            {");
        sb.AppendLine($"                return ({method.ReturnType})invokeResult.Value!;");
        sb.AppendLine("            }");
        sb.AppendLine("            return result;");
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
