using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Csanno.Generator.Models;

namespace Csanno.Generator.Emit;

/// <summary>
/// 组件注册代码发射器
/// </summary>
internal sealed class RegistrationEmitter
{
    public string GenerateRegistrationClass(
        string assemblyName,
        IEnumerable<ComponentInfo> components)
    {
        var sb = new StringBuilder();

        // 文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Assembly: {assemblyName}");
        sb.AppendLine();
        sb.AppendLine("using Autofac;");
        sb.AppendLine();

        // 命名空间和类
        sb.AppendLine($"namespace Csanno.ComponentRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static partial class ComponentRegistrationExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterGeneratedComponents(this ContainerBuilder builder)");
        sb.AppendLine("        {");

        // 生成每个组件的注册
        foreach (var component in components.OrderBy(c => c.ClassName))
        {
            GenerateComponentRegistration(sb, component);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateComponentRegistration(
        StringBuilder sb,
        ComponentInfo component)
    {
        sb.AppendLine($"            // {component.FullTypeName}");
        sb.Append($"            builder.RegisterType<{component.FullTypeName}>()");

        // 生命周期
        sb.Append(GetLifetimeMethod(component.Lifetime, component));

        // 服务映射
        foreach (var service in component.Services.Where(s => !s.IsSelf))
        {
            sb.AppendLine();
            sb.Append($"                .As<{service.ServiceType}>()");
        }

        // 元数据
        foreach (var metadata in component.Metadata)
        {
            sb.AppendLine();
            sb.Append($"                .WithMetadata(\"{metadata.Key}\", {metadata.ValueExpression})");
        }

        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static string GetLifetimeMethod(InstanceLifetime lifetime, ComponentInfo component)
    {
        return lifetime switch
        {
            InstanceLifetime.Transient => ".InstancePerDependency()",
            InstanceLifetime.Scoped => ".InstancePerLifetimeScope()",
            InstanceLifetime.Singleton => ".SingleInstance()",
            InstanceLifetime.PerRequest => ".InstancePerRequest()",
            InstanceLifetime.PerMatchingLifetimeScope =>
                $".InstancePerMatchingLifetimeScope({string.Join(", ", component.LifetimeScopeTags?.Select(t => $"\"{t}\"") ?? Enumerable.Empty<string>())})",
            InstanceLifetime.Owned =>
                $".InstancePerOwned<{component.OwnedTypeName ?? component.FullTypeName}>()",
            _ => ".InstancePerDependency()"
        };
    }
}
