using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Csanno.Generator.Models;
using Csanno.Generator.Emit;
using System.Collections.Immutable;

namespace Csanno.Generator;

/// <summary>
/// Csanno 组件注册代码生成器
/// 使用 Roslyn Source Generator 在编译期生成 Autofac 组件注册代码
/// </summary>
[Generator]
public sealed class ComponentGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册一个简单的调试输出 - 总是生成
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {
                var code = @"// <auto-generated/>
// Generator was loaded and executed at " + System.DateTime.UtcNow.ToString("o") + @"
// Assembly: " + compilation.AssemblyName + @"

namespace Csanno.Generated
{
    public static class GeneratorLoaded
    {
        public const bool IsLoaded = true;
        public const string LoadedAt = """ + System.DateTime.UtcNow.ToString("o") + @""";
    }
}
";
                spc.AddSource("GeneratorLoaded.g.cs", code);
            });

        // 查找带 [Component] 特性的类
        var componentDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => TryGetComponentInfo(ctx)
            )
            .Where(static m => m is not null);

        var compilationAndComponents = context.CompilationProvider
            .Combine(componentDeclarations.Collect());

        context.RegisterSourceOutput(
            compilationAndComponents,
            static (spc, source) => GenerateCode(spc, source.Right)
        );
    }

    private static ComponentInfo? TryGetComponentInfo(GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node);
        if (symbol is null)
        {
            return null;
        }

        // 确保是类类型
        if (symbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        // 排除静态类
        if (classSymbol.IsStatic)
        {
            return null;
        }

        // 排除接口
        if (classSymbol.TypeKind == TypeKind.Interface)
        {
            return null;
        }

        // 排除抽象类
        if (classSymbol.IsAbstract)
        {
            return null;
        }

        // 排除没有公共构造函数的类（Autofac 无法实例化）
        if (!HasPublicConstructor(classSymbol))
        {
            return null;
        }

        // 检查 [Component] 特性 - 使用多种匹配方式
        var hasComponent = classSymbol.GetAttributes()
            .Any(a =>
            {
                var name = a.AttributeClass?.Name;
                var fullName = a.AttributeClass?.ToDisplayString();
                return name == "ComponentAttribute" ||
                       fullName == "Csanno.Attributes.ComponentAttribute" ||
                       fullName?.EndsWith(".ComponentAttribute") == true;
            });

        if (!hasComponent)
        {
            return null;
        }

        return ExtractComponentInfo(classSymbol);
    }

    private static bool HasPublicConstructor(INamedTypeSymbol classSymbol)
    {
        // 检查是否有至少一个公共构造函数
        return classSymbol.Constructors.Any(c => c.DeclaredAccessibility is Accessibility.Public);
    }

    private static ComponentInfo ExtractComponentInfo(INamedTypeSymbol classSymbol)
    {
        return new ComponentInfo
        {
            AssemblyName = classSymbol.ContainingAssembly.Name,
            Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName = classSymbol.Name,
            FullTypeName = classSymbol.ToDisplayString(),
            Lifetime = ResolveLifetime(classSymbol, out var tags, out var ownedType),
            LifetimeScopeTags = tags,
            OwnedTypeName = ownedType,
            Services = ResolveServiceTypes(classSymbol),
            Metadata = ResolveMetadata(classSymbol)
        };
    }

    private static InstanceLifetime ResolveLifetime(
        INamedTypeSymbol classSymbol,
        out string[]? tags,
        out string? ownedType)
    {
        tags = null;
        ownedType = null;

        var attributes = classSymbol.GetAttributes();
        var attrNames = new HashSet<string>(attributes.Select(a => a.AttributeClass?.Name).Where(n => n != null)!);

        if (attrNames.Contains("SingletonAttribute"))
        {
            return InstanceLifetime.Singleton;
        }

        if (attrNames.Contains("ScopedAttribute"))
        {
            return InstanceLifetime.Scoped;
        }

        if (attrNames.Contains("PerRequestAttribute"))
        {
            return InstanceLifetime.PerRequest;
        }

        var perMatching = attributes.FirstOrDefault(a =>
            a.AttributeClass?.Name == "PerMatchingLifetimeScopeAttribute");
        if (perMatching != null)
        {
            tags = perMatching.ConstructorArguments
                .SelectMany(a => a.Values)
                .Select(v => v.Value?.ToString())
                .OfType<string>()
                .ToArray();
            return InstanceLifetime.PerMatchingLifetimeScope;
        }

        var ownedAttr = attributes.FirstOrDefault(a =>
            a.AttributeClass?.Name == "OwnedAttribute");
        if (ownedAttr != null)
        {
            var ownedTypeProp = ownedAttr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == "OwnedType");
            if (ownedTypeProp.Value.Value is INamedTypeSymbol typeSymbol)
            {
                ownedType = typeSymbol.ToDisplayString();
            }
            return InstanceLifetime.Owned;
        }

        if (attrNames.Contains("TransientAttribute"))
        {
            return InstanceLifetime.Transient;
        }

        return InstanceLifetime.Transient;  // 默认
    }

    private static List<ServiceInfo> ResolveServiceTypes(INamedTypeSymbol classSymbol)
    {
        var services = new List<ServiceInfo>();

        // [AsService] 特性
        var asServiceAttrs = classSymbol.GetAttributes()
            .Where(a => a.AttributeClass?.Name == "AsServiceAttribute");

        foreach (var attr in asServiceAttrs)
        {
            var serviceType = attr.ConstructorArguments.FirstOrDefault().Value;
            if (serviceType is INamedTypeSymbol typeSymbol)
            {
                services.Add(new ServiceInfo
                {
                    ServiceType = typeSymbol.ToDisplayString(),
                    IsSelf = SymbolEqualityComparer.Default.Equals(typeSymbol, classSymbol)
                });
            }
        }

        // 检查 ComponentAttribute.ServiceType
        var componentAttr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "ComponentAttribute");
        if (componentAttr != null)
        {
            var serviceTypeProp = componentAttr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == "ServiceType");
            if (serviceTypeProp.Value.Value is INamedTypeSymbol propType)
            {
                services.Clear();
                services.Add(new ServiceInfo
                {
                    ServiceType = propType.ToDisplayString(),
                    IsSelf = SymbolEqualityComparer.Default.Equals(propType, classSymbol)
                });
                return services;
            }
        }

        // 默认注册为自身
        if (services.Count == 0)
        {
            services.Add(new ServiceInfo
            {
                ServiceType = classSymbol.ToDisplayString(),
                IsSelf = true
            });
        }

        return services;
    }

    private static List<MetadataInfo> ResolveMetadata(INamedTypeSymbol classSymbol)
    {
        return classSymbol.GetAttributes()
            .Where(a => a.AttributeClass?.Name == "WithMetadataAttribute")
            .Select(attr =>
            {
                var key = attr.ConstructorArguments[0].Value?.ToString() ?? string.Empty;
                var value = attr.ConstructorArguments[1];

                return new MetadataInfo
                {
                    Key = key,
                    ValueExpression = ConvertToAotFriendlyExpression(value)
                };
            })
            .ToList();
    }

    private static string ConvertToAotFriendlyExpression(TypedConstant value)
    {
        if (value.Value is null)
        {
            return "null";
        }

        if (value.Value is string s)
        {
            return $"\"{s}\"";
        }

        if (value.Value is bool b)
        {
            return b ? "true" : "false";
        }

        if (value.Value is int i)
        {
            return i.ToString();
        }

        if (value.Value is INamedTypeSymbol type)
        {
            return $"typeof({type.ToDisplayString()})";
        }

        return "null";  // 不支持的类型默认为 null
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ComponentInfo?> components)
    {
        var validComponents = components.OfType<ComponentInfo>().ToList();

        // 调试输出：生成器运行状态
        var debugInfo = new StringBuilder();
        debugInfo.AppendLine("// Source Generator Debug Info");
        debugInfo.AppendLine($"// Total candidates: {components.Length}");
        debugInfo.AppendLine($"// Valid components: {validComponents.Count}");
        debugInfo.AppendLine("// Components found:");
        foreach (var c in validComponents)
        {
            debugInfo.AppendLine($"//   - {c.FullTypeName}");
        }

        if (!validComponents.Any())
        {
            context.AddSource(
                "GeneratorDebug.g.cs",
                debugInfo.ToString());
            return;
        }

        foreach (var group in validComponents.GroupBy(c => c.AssemblyName))
        {
            var emitter = new RegistrationEmitter();
            var code = emitter.GenerateRegistrationClass(group.Key, group);

            context.AddSource(
                $"ComponentRegistration.{group.Key}.g.cs",
                code);
        }

        // 生成调试信息
        context.AddSource("GeneratorDebug.g.cs", debugInfo.ToString());
    }
}
